# SPDX-License-Identifier: GPL-2.0-only

CFLAGS_init.o := -mcmodel=medany

obj-y += init.o
obj-y += extable.o
obj-y += cacheflush.o
obj-y += context.o
obj-y += tlbflush.o
obj-y += hugetlbpage.o

obj-y += fault.o #pageattr.o
