# SPDX-License-Identifier: GPL-2.0
# Any varying coverage in these files is non-deterministic
# and is generally not a function of system call inputs.

obj-y += mutex.o semaphore.o rwsem.o
obj-$(CONFIG_SMP) += spinlock.o
