# SPDX-License-Identifier: GPL-2.0
obj-y	+= tty_io.o tty_port.o tty_buffer.o tty_baudrate.o tty_ioctl.o
obj-y	+= n_tty.o tty_ldisc.o tty_jobctrl.o tty_mutex.o tty_ldsem.o
obj-y	+= serial/
obj-y	+= vt/
