# SPDX-License-Identifier: GPL-2.0
obj-y = base.o platform.o property.o #device.o
obj-y += address.o
obj-y += of_reserved_mem.o
obj-y += irq.o
obj-$(CONFIG_OF_KOBJ) += kobj.o
obj-$(CONFIG_OF_FLATTREE) += fdt.o
