// SPDX-License-Identifier: GPL-2.0

// Generated by scripts/atomic/gen-atomic-fallback.sh
// DO NOT MODIFY THIS FILE DIRECTLY

#ifndef _LINUX_ATOMIC_FALLBACK_H
#define _LINUX_ATOMIC_FALLBACK_H

#include <linux/compiler.h>

#ifndef atomic_inc
static __always_inline void
atomic_inc(atomic_t *v)
{
    atomic_add(1, v);
}
#define atomic_inc atomic_inc
#endif

#ifndef atomic_dec
static __always_inline void
atomic_dec(atomic_t *v)
{
    atomic_sub(1, v);
}
#define atomic_dec atomic_dec
#endif

#endif /* _LINUX_ATOMIC_FALLBACK_H */
