# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the kernel block layer
#

obj-y	:= #bdev.o fops.o bio.o elevator.o blk-core.o blk-sysfs.o
obj-y 	+= blk-mq.o blk-mq-tag.o blk-mq-cpumap.o
obj-y 	+= blk-mq-virtio.o
