# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Linux filesystems.
#
# 14 Sep 2000, Christoph Hellwig <hch@infradead.org>
# Rewritten to use lists instead of if-statements.
#

obj-y := open.o read_write.o inode.o super.o filesystems.o libfs.o dcache.o
obj-y += namespace.o file.o
obj-y += fs_context.o fs_parser.o fs_struct.o namei.o init.o exec.o
obj-y += char_dev.o splice.o buffer.o bad_inode.o mpage.o file_table.o

obj-y += ramfs/
obj-y += ext2/
