# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Linux filesystems.
#
# 14 Sep 2000, Christoph Hellwig <hch@infradead.org>
# Rewritten to use lists instead of if-statements.
#

obj-y := read_write.o inode.o super.o filesystems.o libfs.o dcache.o namespace.o
obj-y += fs_context.o fs_parser.o fs_struct.o namei.o init.o
obj-y += char_dev.o

obj-y += ramfs/

