# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Linux kernel device drivers.
#

obj-y               += irqchip/
obj-y               += base/
obj-y               += tty/
obj-y               += virtio/
obj-$(CONFIG_OF)	+= of/
