# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the linux ext2-filesystem routines.
#

obj-y += ext2.o

ext2-y := #balloc.o dir.o file.o ialloc.o inode.o
ext2-y += super.o #ioctl.o namei.o symlink.o
