# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the linux ext2-filesystem routines.
#

obj-y += ext2.o

ext2-y := balloc.o ialloc.o inode.o dir.o file.o
ext2-y += super.o namei.o ioctl.o #symlink.o
