# SPDX-License-Identifier: GPL-2.0
obj-y += time.o timer.o hrtimer.o
obj-y += clocksource.o jiffies.o timekeeping.o ntp.o #timer_list.o
obj-y += tick-oneshot.o tick-sched.o
obj-y += tick-common.o clockevents.o
obj-y += sched_clock.o tick-broadcast.o
obj-y += posix-timers.o posix-cpu-timers.o posix-clock.o itimer.o
