# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the linux ipc.
#

obj-y += shm.o #util.o msgutil.o msg.o sem.o syscall.o
#obj-y += ipc_sysctl.o
#obj-y += mqueue.o msgutil.o
#obj-y += namespace.o
#obj-y += mq_sysctl.o
