# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Linux proc filesystem routines.
#

obj-y   += proc.o

proc-y	:= #nommu.o task_nommu.o
proc-y	+= inode.o root.o base.o generic.o #array.o fd.o
proc-y  += self.o
proc-y  += util.o
